# These are supported funding model platforms

# github: [darkfriend]
custom: [
  'https://yoomoney.ru/to/410011413398643',
  'https://www.tinkoff.ru/cf/36wVfnMf7mo',
  'https://paypal.me/darkfriend'
]
